# Generated by Django 4.1 on 2022-08-24 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='default.png', upload_to='static/thumbnails'),
        ),
    ]
